coverage:
    status:
        project:
            default:
                # basic
                target: auto
                threshold: 7%
        patch:
            default:
                # basic
                target: auto
                threshold: 7%
