name: test uip proposals

on:
    push:
        branches:
            - "uip/**"
jobs:
    buildAndSimulate:
        name: Build and Simulate
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Install Dependencies
              run: npm install

            - name: Simulate on mainnet
              run: |
                  npm run test proposals/**/testProposal.js
              env:
                  COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
                  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
                  INFURA_ID: ${{ secrets.INFURA_ID }}
                  MNEMONIC_TEST: ${{ secrets.MNEMONIC_TEST }}
